### ISSUE TITLE
Usage in Browser

### ISSUE THREAD

**Issue by aryst** [hokein/Automata.js#8]
hye, 
i really need help to use this in the browser. i have been trying whole day for this but seem not working. maybe i miss some important part.

**Comment by moghya** [comment]
@hokein any updates?
I tried to use browserify but not able to use in browser the generated bundle doesn't seem to work. Examples will be really appreciated.

**Comment by moghya** [comment]
browserify doesn't seem to generate correct bundle,

I compared between generated `regparser-browser.js` file and file at this [demo](http://hokein.github.io/Automata.js/regparser-browser.js), here is the [difference](https://www.diffchecker.com/fDSjAqss).

**Comment by hokein** [comment]
The `browserify` seems work for me (`make distribution`). Maybe relate to the browserify version? The repository is currently using a pretty old version of browserify.

The source code of the sample page is located in https://github.com/hokein/Automata.js/tree/gh-pages.
