### ISSUE TITLE
Major issue when dealing with many terminal states

### ISSUE THREAD

**Issue by ClementNerma** [hokein/Automata.js#9]
While using your program, I tried for fun to write the following expression: `a|b|c|...|z`. I got an unexpected result (a very strange automata), so to debug it a little I ran it step by step.

So, when I use "Compile to DFA" with `a|b|c|d|e|f`, everything is fine:

![Working example](https://i.snag.gy/9DEpfj.jpg)

But if I simply add a `g` option (`a|b|c|d|e|f|g`), a strange result happens:

![Unexpected result](https://i.snag.gy/d7CqnU.jpg)

A crazy result is when I write `a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z|0|1|2|3|4|5`. Here's an extract of the drawn automata:

![Crazy result](https://i.snag.gy/2UM8nR.jpg)

This is really strange, any idea of what happens?

**Comment by hokein** [comment]
Looks like a bug when converting NFA to DFA.

**Comment by G-Ricky** [comment]
Hello, I think I found it. It was in function _reorderNFAStateId

> Automata.js/src/regparser.js:283
> RegParser.prototype._reorderNFAStateId = function() {

When you dynamically change `state.id`, it may miss some nodes to change id or repeatedly change the same node.It is likely to be in the case of multiple branches converging in NFA.

Result of NFA of `A|B|C|D|E|F|G`

With _reorderNFAStateId()
![](http://wx2.sinaimg.cn/large/916d0ca4gy1fruscps8rjj21en0cjq4v.jpg)

Without _reorderNFAStateId()
![](http://wx3.sinaimg.cn/large/916d0ca4gy1frusca5wj3j21fe0d9tai.jpg)

It seems that node 10 is the missing one

Suggestion:
Optimize algorithm of ordering
Or separate state id and node name

**Comment by hokein** [comment]
@G-Ricky Thanks for your investigation, it is really helpful!
It seems like a bug in `_reorderNFAStateId`, since you have figured out the root cause, do you mind sending a PR fixing it?
